export const LANGUAGES = [
  "Afrikaans",
  "Albanian", 
  "Arabic",
  "Armenian",
  "Azerbaijani",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bosnian",
  "Bulgarian",
  "Catalan",
  "Chinese (Simplified)",
  "Chinese (Traditional)",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Estonian",
  "Filipino",
  "Finnish",
  "French",
  "Galician",
  "Georgian",
  "German",
  "Greek",
  "Gujarati",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Indonesian",
  "Irish",
  "Italian",
  "Japanese",
  "Kannada",
  "Kazakh",
  "Korean",
  "Latvian",
  "Lithuanian",
  "Luxembourgish",
  "Macedonian",
  "Malay",
  "Malayalam",
  "Maltese",
  "Marathi",
  "Norwegian",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Romanian",
  "Russian",
  "Serbian",
  "Slovak",
  "Slovenian",
  "Spanish",
  "Swahili",
  "Swedish",
  "Tamil",
  "Telugu",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Vietnamese",
  "Welsh"
];

export const getLanguageCode = (language: string): string => {
  const languageMap: { [key: string]: string } = {
    "Afrikaans": "AF",
    "Albanian": "SQ", 
    "Arabic": "AR",
    "Armenian": "HY",
    "Azerbaijani": "AZ",
    "Basque": "EU",
    "Belarusian": "BE",
    "Bengali": "BN",
    "Bosnian": "BS",
    "Bulgarian": "BG",
    "Catalan": "CA",
    "Chinese (Simplified)": "ZH",
    "Chinese (Traditional)": "ZH",
    "Croatian": "HR",
    "Czech": "CS",
    "Danish": "DA",
    "Dutch": "NL",
    "English": "EN",
    "Estonian": "ET",
    "Filipino": "FI",
    "Finnish": "FI",
    "French": "FR",
    "Galician": "GL",
    "Georgian": "KA",
    "German": "DE",
    "Greek": "EL",
    "Gujarati": "GU",
    "Hebrew": "HE",
    "Hindi": "HI",
    "Hungarian": "HU",
    "Icelandic": "IS",
    "Indonesian": "ID",
    "Irish": "GA",
    "Italian": "IT",
    "Japanese": "JA",
    "Kannada": "KN",
    "Kazakh": "KK",
    "Korean": "KO",
    "Latvian": "LV",
    "Lithuanian": "LT",
    "Luxembourgish": "LB",
    "Macedonian": "MK",
    "Malay": "MS",
    "Malayalam": "ML",
    "Maltese": "MT",
    "Marathi": "MR",
    "Norwegian": "NO",
    "Persian": "FA",
    "Polish": "PL",
    "Portuguese": "PT",
    "Punjabi": "PA",
    "Romanian": "RO",
    "Russian": "RU",
    "Serbian": "SR",
    "Slovak": "SK",
    "Slovenian": "SL",
    "Spanish": "ES",
    "Swahili": "SW",
    "Swedish": "SV",
    "Tamil": "TA",
    "Telugu": "TE",
    "Thai": "TH",
    "Turkish": "TR",
    "Ukrainian": "UK",
    "Urdu": "UR",
    "Vietnamese": "VI",
    "Welsh": "CY"
  };
  
  return languageMap[language] || "EN";
};